services:
  postgres:
    container_name: weather_data_providers_db
    image: postgres
    ports:
    - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
    - POSTGRES_USER=postgres-user
    - POSTGRES_PASSWORD=postgres-password
volumes:
    db: